name: run main.py

permissions: # allow the action to push changes to the repository
  contents: write
  pull-requests: write
  issues: write

on:
  schedule:
    - cron: '50 12 * * *' # At 08:00 UTC each day

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run main.py
        run: python main.py

      - name: commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --quiet HEAD || (git commit -a -m "updated table" --allow-empty) 
          
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
          branch: main

  rebuild-pages:
    needs: build
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2
        with:
            ref: gh-pages # Checkout the gh-pages branch
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
            node-version: '14'
        
      - name: Build and deploy GitHub Pages
        run: |
            npm install
            npm run build
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git diff --quiet HEAD || (git commit -a -m "Rebuilt GitHub Pages" --allow-empty)
            git push